import { Employee, Visit } from './types';

export const INITIAL_EMPLOYEES: Employee[] = [
  {
    id: 'emp-1',
    empId: 'INV-101',
    name: 'Amit Verma',
    mobileNumber: '9826012345',
    designation: 'Senior Field Officer',
    district: 'Betul',
    territory: 'Multai',
    dailyVisitTarget: 10,
    isActive: true,
  },
  {
    id: 'emp-2',
    empId: 'INV-102',
    name: 'Rajesh Sharma',
    mobileNumber: '9826023456',
    designation: 'Territory Executive',
    district: 'Betul',
    territory: 'Amla & Betul',
    dailyVisitTarget: 10,
    isActive: true,
  },
  {
    id: 'emp-3',
    empId: 'INV-103',
    name: 'Sunil Chouhan',
    mobileNumber: '9826034567',
    designation: 'Field Officer',
    district: 'Chhindwara',
    territory: 'Sausar & Pandhurna',
    dailyVisitTarget: 8,
    isActive: true,
  },
  {
    id: 'emp-4',
    empId: 'INV-104',
    name: 'Pooja Patel',
    mobileNumber: '9826045678',
    designation: 'Agronomist & Field Lead',
    district: 'Chhindwara',
    territory: 'Chhindwara Central',
    dailyVisitTarget: 8,
    isActive: true,
  },
  {
    id: 'emp-5',
    empId: 'INV-105',
    name: 'Manoj Deshmukh',
    mobileNumber: '9826056789',
    designation: 'Senior Field Officer',
    district: 'Amravati',
    territory: 'Morshi & Warud',
    dailyVisitTarget: 10,
    isActive: true,
  },
  {
    id: 'emp-6',
    empId: 'INV-106',
    name: 'Kiran Wankhede',
    mobileNumber: '9826067890',
    designation: 'Field Officer',
    district: 'Amravati',
    territory: 'Achalpur & Chandur',
    dailyVisitTarget: 8,
    isActive: true,
  },
  {
    id: 'emp-7',
    empId: 'INV-107',
    name: 'Vikas Raghuvanshi',
    mobileNumber: '9826078901',
    designation: 'Territory Manager',
    district: 'Hoshangabad',
    territory: 'Pipariya & Sohagpur',
    dailyVisitTarget: 10,
    isActive: true,
  },
  {
    id: 'emp-8',
    empId: 'INV-108',
    name: 'Deepak Tiwari',
    mobileNumber: '9826089012',
    designation: 'Field Officer',
    district: 'Harda',
    territory: 'Timarni & Khirkiya',
    dailyVisitTarget: 8,
    isActive: true,
  },
  {
    id: 'emp-9',
    empId: 'INV-109',
    name: 'Suresh Patil',
    mobileNumber: '9826090123',
    designation: 'Senior Field Officer',
    district: 'Nagpur',
    territory: 'Katol & Narkhed',
    dailyVisitTarget: 10,
    isActive: true,
  },
  {
    id: 'emp-10',
    empId: 'INV-110',
    name: 'Anil Yadav',
    mobileNumber: '9826101234',
    designation: 'Field Officer',
    district: 'Sehore',
    territory: 'Ashta & Ichhawar',
    dailyVisitTarget: 8,
    isActive: true,
  },
  // Adding remaining 50 officers systematically across key clusters
  ...Array.from({ length: 50 }, (_, i) => {
    const idx = i + 11;
    const districts = ['Betul', 'Chhindwara', 'Amravati', 'Nagpur', 'Hoshangabad', 'Harda', 'Sehore', 'Dewas', 'Indore', 'Jabalpur', 'Khandwa', 'Khargone'];
    const names = [
      'Gopal Singh', 'Dharmendra Joshi', 'Pravin Pawar', 'Rameshwar Meena', 'Santosh Kushwaha',
      'Nitin Bisen', 'Pankaj Thakur', 'Sachin Kapse', 'Vinod Rathore', 'Ashok Malviya',
      'Mahesh Kale', 'Rahul Mandloi', 'Kamlesh Dangi', 'Yogesh Gour', 'Bhupendra Lodhi',
      'Chetan Solanki', 'Hemant Soni', 'Jagdish Baghel', 'Lokesh Sen', 'Mukesh Barman',
      'Narendra Patidar', 'Omkar Shinde', 'Pradeep Vishwakarma', 'Radheshyam Gupta', 'Sandip Gaikwad',
      'Tarun Mukati', 'Umesh Pal', 'Vijay Bisen', 'Vivek Dubey', 'Ajay Nimawat',
      'Balram Chouhan', 'Chandra Shekhar', 'Devendra Rawat', 'Girish Verma', 'Hariom Sahu',
      'Inderjeet Patel', 'Jitendra Kosta', 'Kuldeep Parihar', 'Laxman Dhangar', 'Mohanlal Silawat',
      'Navneet Mishra', 'Pawan Kewat', 'Radha Raman', 'Sanjay Goud', 'Tejpal Solanki',
      'Uday Bhan', 'Vikramaditya Rao', 'Wasim Khan', 'Yuvraj Sisodiya', 'Zahid Ansari'
    ];
    const dist = districts[i % districts.length];
    return {
      id: `emp-${idx}`,
      empId: `INV-${100 + idx}`,
      name: names[i] || `Field Officer ${idx}`,
      mobileNumber: `9826${(100000 + idx * 739).toString().slice(0, 6)}`,
      designation: idx % 4 === 0 ? 'Senior Field Officer' : idx % 5 === 0 ? 'Territory Executive' : 'Field Officer',
      district: dist,
      territory: `${dist} Zone-${(idx % 3) + 1}`,
      dailyVisitTarget: 8 + (idx % 3) * 2, // 8, 10, or 12
      isActive: true,
    };
  }),
];

export const INITIAL_VISITS: Visit[] = [];
