import { Employee, Visit } from './types';

export const INITIAL_EMPLOYEES: Employee[] = [
  {
    id: 'emp-1',
    empId: 'INV-101',
    name: 'Amit Verma',
    mobileNumber: '9826012345',
    designation: 'Senior Field Officer',
    district: 'Betul',
    territory: 'Multai',
    dailyVisitTarget: 10,
    isActive: true,
  },
  {
    id: 'emp-2',
    empId: 'INV-102',
    name: 'Rajesh Sharma',
    mobileNumber: '9826023456',
    designation: 'Territory Executive',
    district: 'Betul',
    territory: 'Amla & Betul',
    dailyVisitTarget: 10,
    isActive: true,
  },
  {
    id: 'emp-3',
    empId: 'INV-103',
    name: 'Sunil Chouhan',
    mobileNumber: '9826034567',
    designation: 'Field Officer',
    district: 'Chhindwara',
    territory: 'Sausar & Pandhurna',
    dailyVisitTarget: 8,
    isActive: true,
  },
  {
    id: 'emp-4',
    empId: 'INV-104',
    name: 'Pooja Patel',
    mobileNumber: '9826045678',
    designation: 'Agronomist & Field Lead',
    district: 'Chhindwara',
    territory: 'Chhindwara Central',
    dailyVisitTarget: 8,
    isActive: true,
  },
  {
    id: 'emp-5',
    empId: 'INV-105',
    name: 'Manoj Deshmukh',
    mobileNumber: '9826056789',
    designation: 'Senior Field Officer',
    district: 'Amravati',
    territory: 'Morshi & Warud',
    dailyVisitTarget: 10,
    isActive: true,
  },
  {
    id: 'emp-6',
    empId: 'INV-106',
    name: 'Kiran Wankhede',
    mobileNumber: '9826067890',
    designation: 'Field Officer',
    district: 'Amravati',
    territory: 'Achalpur & Chandur',
    dailyVisitTarget: 8,
    isActive: true,
  },
  {
    id: 'emp-7',
    empId: 'INV-107',
    name: 'Vikas Raghuvanshi',
    mobileNumber: '9826078901',
    designation: 'Territory Manager',
    district: 'Hoshangabad',
    territory: 'Pipariya & Sohagpur',
    dailyVisitTarget: 10,
    isActive: true,
  },
  {
    id: 'emp-8',
    empId: 'INV-108',
    name: 'Deepak Tiwari',
    mobileNumber: '9826089012',
    designation: 'Field Officer',
    district: 'Harda',
    territory: 'Timarni & Khirkiya',
    dailyVisitTarget: 8,
    isActive: true,
  },
  {
    id: 'emp-9',
    empId: 'INV-109',
    name: 'Suresh Patil',
    mobileNumber: '9826090123',
    designation: 'Senior Field Officer',
    district: 'Nagpur',
    territory: 'Katol & Narkhed',
    dailyVisitTarget: 10,
    isActive: true,
  },
  {
    id: 'emp-10',
    empId: 'INV-110',
    name: 'Anil Yadav',
    mobileNumber: '9826101234',
    designation: 'Field Officer',
    district: 'Sehore',
    territory: 'Ashta & Ichhawar',
    dailyVisitTarget: 8,
    isActive: true,
  },
  // Adding remaining 50 officers systematically across key clusters
  ...Array.from({ length: 50 }, (_, i) => {
    const idx = i + 11;
    const districts = ['Betul', 'Chhindwara', 'Amravati', 'Nagpur', 'Hoshangabad', 'Harda', 'Sehore', 'Dewas', 'Indore', 'Jabalpur', 'Khandwa', 'Khargone'];
    const names = [
      'Gopal Singh', 'Dharmendra Joshi', 'Pravin Pawar', 'Rameshwar Meena', 'Santosh Kushwaha',
      'Nitin Bisen', 'Pankaj Thakur', 'Sachin Kapse', 'Vinod Rathore', 'Ashok Malviya',
      'Mahesh Kale', 'Rahul Mandloi', 'Kamlesh Dangi', 'Yogesh Gour', 'Bhupendra Lodhi',
      'Chetan Solanki', 'Hemant Soni', 'Jagdish Baghel', 'Lokesh Sen', 'Mukesh Barman',
      'Narendra Patidar', 'Omkar Shinde', 'Pradeep Vishwakarma', 'Radheshyam Gupta', 'Sandip Gaikwad',
      'Tarun Mukati', 'Umesh Pal', 'Vijay Bisen', 'Vivek Dubey', 'Ajay Nimawat',
      'Balram Chouhan', 'Chandra Shekhar', 'Devendra Rawat', 'Girish Verma', 'Hariom Sahu',
      'Inderjeet Patel', 'Jitendra Kosta', 'Kuldeep Parihar', 'Laxman Dhangar', 'Mohanlal Silawat',
      'Navneet Mishra', 'Pawan Kewat', 'Radha Raman', 'Sanjay Goud', 'Tejpal Solanki',
      'Uday Bhan', 'Vikramaditya Rao', 'Wasim Khan', 'Yuvraj Sisodiya', 'Zahid Ansari'
    ];
    const dist = districts[i % districts.length];
    return {
      id: `emp-${idx}`,
      empId: `INV-${100 + idx}`,
      name: names[i] || `Field Officer ${idx}`,
      mobileNumber: `9826${(100000 + idx * 739).toString().slice(0, 6)}`,
      designation: idx % 4 === 0 ? 'Senior Field Officer' : idx % 5 === 0 ? 'Territory Executive' : 'Field Officer',
      district: dist,
      territory: `${dist} Zone-${(idx % 3) + 1}`,
      dailyVisitTarget: 8 + (idx % 3) * 2, // 8, 10, or 12
      isActive: true,
    };
  }),
];

export const INITIAL_VISITS: Visit[] = [
  {
    id: 'v-101',
    employeeId: 'emp-1',
    employeeName: 'Amit Verma',
    employeeMobile: '9826012345',
    district: 'Betul',
    territory: 'Multai',
    visitType: 'Dealer Visit',
    entityName: 'Shiv Shakti Krishi Kendra',
    village: 'Multai',
    latitude: 21.7709,
    longitude: 78.2575,
    locationName: 'Main Road, Multai',
    photoUrl: 'https://images.unsplash.com/photo-1592417817098-8f3d6eb22513?w=600&auto=format&fit=crop&q=80',
    remarksBooking: 'Innoveg 108 – 20 Bags Requirement booked for immediate dispatch',
    isRepeatLocation: false,
    distanceFromPrevKm: 0,
    aiAnalysis: {
      qualityScore: 92,
      isBlur: false,
      fieldVisible: false,
      personVisible: true,
      brandingVisible: true,
      visitTypeMatch: true,
      summaryHindi: '✅ डीलर शॉप काउंटर और इनर/आउटर ब्रांडिंग स्पष्ट रूप से दिखाई दे रही है।',
      summaryEnglish: 'Dealer store counter with InnoVeg seed posters and stock shelf visible.',
      tags: ['Dealer / Partner', 'InnoVeg Branding', 'High Clarity'],
    },
    timestamp: new Date(Date.now() - 6 * 3600 * 1000).toISOString(),
  },
  {
    id: 'v-102',
    employeeId: 'emp-1',
    employeeName: 'Amit Verma',
    employeeMobile: '9826012345',
    district: 'Betul',
    territory: 'Multai',
    visitType: 'Farmer Visit',
    entityName: 'Rameshwar Ji Patel',
    village: 'Dunawa',
    latitude: 21.7345,
    longitude: 78.4123,
    locationName: 'Dunawa Village Farmland',
    photoUrl: 'https://images.unsplash.com/photo-1595974482597-4b8da8879bc5?w=600&auto=format&fit=crop&q=80',
    remarksBooking: 'Farmer satisfied with InnoVeg Tomato germination. 5 Acres planting planned.',
    isRepeatLocation: false,
    distanceFromPrevKm: 22.4,
    aiAnalysis: {
      qualityScore: 88,
      isBlur: false,
      fieldVisible: true,
      personVisible: true,
      brandingVisible: false,
      visitTypeMatch: true,
      summaryHindi: '✅ खेत में किसान के साथ फसल का निरीक्षण स्पष्ट दिखाई दे रहा है।',
      summaryEnglish: 'Farmer standing beside vigorous vegetable nursery plot.',
      tags: ['Farm Canopy', 'Farmer / Officer', 'High Clarity'],
    },
    timestamp: new Date(Date.now() - 4.5 * 3600 * 1000).toISOString(),
  },
  {
    id: 'v-103',
    employeeId: 'emp-1',
    employeeName: 'Amit Verma',
    employeeMobile: '9826012345',
    district: 'Betul',
    territory: 'Multai',
    visitType: 'Field Program',
    entityName: 'Farmer Group Demonstration Meeting',
    village: 'Masod',
    latitude: 21.6512,
    longitude: 78.3411,
    locationName: 'Panchayat Bhavan, Masod',
    photoUrl: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=600&auto=format&fit=crop&q=80',
    remarksBooking: 'Attended by 18 progressive farmers. Product sample demo conducted.',
    isRepeatLocation: false,
    distanceFromPrevKm: 18.2,
    aiAnalysis: {
      qualityScore: 95,
      isBlur: false,
      fieldVisible: true,
      personVisible: true,
      brandingVisible: true,
      visitTypeMatch: true,
      summaryHindi: '✅ फील्ड प्रोग्राम बैनर और 15+ किसान समूह उपस्थिति सत्यापित।',
      summaryEnglish: 'Farmer field day with banner demo and group gathering visible.',
      tags: ['InnoVeg Branding', 'Farmer / Officer', 'High Clarity'],
    },
    timestamp: new Date(Date.now() - 3 * 3600 * 1000).toISOString(),
  },
  {
    id: 'v-104',
    employeeId: 'emp-1',
    employeeName: 'Amit Verma',
    employeeMobile: '9826012345',
    district: 'Betul',
    territory: 'Multai',
    visitType: 'Dealer Visit',
    entityName: 'Shiv Shakti Krishi Kendra (Follow-up)',
    village: 'Multai',
    latitude: 21.7708,
    longitude: 78.2574,
    locationName: 'Main Road, Multai',
    photoUrl: 'https://images.unsplash.com/photo-1592417817098-8f3d6eb22513?w=600&auto=format&fit=crop&q=80',
    remarksBooking: 'Payment collection and delivery schedule confirmation.',
    isRepeatLocation: true, // Proximity < 150m from v-101
    distanceFromPrevKm: 31.1,
    aiAnalysis: {
      qualityScore: 90,
      isBlur: false,
      fieldVisible: false,
      personVisible: true,
      brandingVisible: true,
      visitTypeMatch: true,
      summaryHindi: '✅ डीलर शॉप काउंटर और इनर/आउटर ब्रांडिंग स्पष्ट रूप से दिखाई दे रही है।',
      summaryEnglish: 'Follow-up dealer visit confirmed at retail outlet.',
      tags: ['Dealer / Partner', 'InnoVeg Branding', 'High Clarity'],
    },
    timestamp: new Date(Date.now() - 1.2 * 3600 * 1000).toISOString(),
  },
  {
    id: 'v-105',
    employeeId: 'emp-5',
    employeeName: 'Manoj Deshmukh',
    employeeMobile: '9826056789',
    district: 'Amravati',
    territory: 'Morshi & Warud',
    visitType: 'Dealer Visit',
    entityName: 'Kisan Agro Agency, Warud',
    village: 'Warud',
    latitude: 21.4655,
    longitude: 78.2678,
    locationName: 'Warud Market Yard',
    photoUrl: 'https://images.unsplash.com/photo-1582213782179-e0d53f98f2ca?w=600&auto=format&fit=crop&q=80',
    remarksBooking: 'Orange orchard growers demand high for InnoVeg special nutrition series.',
    isRepeatLocation: false,
    distanceFromPrevKm: 0,
    aiAnalysis: {
      qualityScore: 89,
      isBlur: false,
      fieldVisible: false,
      personVisible: true,
      brandingVisible: true,
      visitTypeMatch: true,
      summaryHindi: '✅ डीलर शॉप काउंटर और इनर/आउटर ब्रांडिंग स्पष्ट रूप से दिखाई दे रही है।',
      summaryEnglish: 'Agro dealer interaction with product display.',
      tags: ['Dealer / Partner', 'InnoVeg Branding', 'High Clarity'],
    },
    timestamp: new Date(Date.now() - 5 * 3600 * 1000).toISOString(),
  },
  {
    id: 'v-106',
    employeeId: 'emp-3',
    employeeName: 'Sunil Chouhan',
    employeeMobile: '9826034567',
    district: 'Chhindwara',
    territory: 'Sausar & Pandhurna',
    visitType: 'Farmer Visit',
    entityName: 'Dhanraj Bhoyar',
    village: 'Berdi',
    latitude: 21.6121,
    longitude: 78.7844,
    locationName: 'Berdi Vegetable Farm',
    photoUrl: 'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?w=600&auto=format&fit=crop&q=80',
    remarksBooking: 'Chilli crop inspection - flower drop issue addressed with recommended dose.',
    isRepeatLocation: false,
    distanceFromPrevKm: 14.5,
    aiAnalysis: {
      qualityScore: 84,
      isBlur: false,
      fieldVisible: true,
      personVisible: true,
      brandingVisible: false,
      visitTypeMatch: true,
      summaryHindi: '✅ खेत में किसान के साथ फसल का निरीक्षण स्पष्ट दिखाई दे रहा है।',
      summaryEnglish: 'Field inspection of chilli crop canopy.',
      tags: ['Farm Canopy', 'Farmer / Officer', 'High Clarity'],
    },
    timestamp: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
  }
];
